### ISSUE TITLE
Error when on_connection_closed called

### ISSUE THREAD

**Issue by ajmaddaford** [ONSdigital/sdx-downstream#6]
I get the following error when on_connection_closed is called. This causes sdx-downstream to die. Looks like it's because we're not passing param=value arguments to structlog logger.
```
sdx-downstream_1          | 2016-07-18 12:42:25,551|ERROR: sdx-downstream: Calling <bound method AsyncConsumer.on_connection_closed of <__main__.Consumer object at 0x7f8b3f122b38>> for "0:_on_connection_closed" failed
sdx-downstream_1          | Traceback (most recent call last):
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/callback.py", line 236, in process
sdx-downstream_1          |     callback(*args, **keywords)
sdx-downstream_1          |   File "/app/async_consumer.py", line 98, in on_connection_closed
sdx-downstream_1          |     reply_code, reply_text)
sdx-downstream_1          | TypeError: _proxy_to_logger() takes from 2 to 3 positional arguments but 5 were given
sdx-downstream_1          | Traceback (most recent call last):
sdx-downstream_1          |   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
sdx-downstream_1          |     "__main__", mod_spec)
sdx-downstream_1          |   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
sdx-downstream_1          |     exec(code, run_globals)
sdx-downstream_1          |   File "/app/consumer.py", line 38, in <module>
sdx-downstream_1          |     main()
sdx-downstream_1          |   File "/app/consumer.py", line 33, in main
sdx-downstream_1          |     consumer.run()
sdx-downstream_1          |   File "/app/async_consumer.py", line 327, in run
sdx-downstream_1          |     self._connection.ioloop.start()
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/adapters/select_connection.py", line 355, in start
sdx-downstream_1          |     self.process_timeouts()
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/adapters/select_connection.py", line 283, in process_timeouts
sdx-downstream_1          |     timer['callback']()
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/heartbeat.py", line 88, in send_and_check
sdx-downstream_1          |     return self._close_connection()
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/heartbeat.py", line 121, in _close_connection
sdx-downstream_1          |     text)
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/connection.py", line 1368, in _on_disconnect
sdx-downstream_1          |     self._process_connection_closed_callbacks(reply_code, reply_text)
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/connection.py", line 1397, in _process_connection_closed_callbacks
sdx-downstream_1          |     reason_code, reason_text)
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/callback.py", line 60, in wrapper
sdx-downstream_1          |     return function(*tuple(args), **kwargs)
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/callback.py", line 92, in wrapper
sdx-downstream_1          |     return function(*args, **kwargs)
sdx-downstream_1          |   File "/usr/local/lib/python3.5/dist-packages/pika/callback.py", line 236, in process
sdx-downstream_1          |     callback(*args, **keywords)
sdx-downstream_1          |   File "/app/async_consumer.py", line 98, in on_connection_closed
sdx-downstream_1          |     reply_code, reply_text)
sdx-downstream_1          | TypeError: _proxy_to_logger() takes from 2 to 3 positional arguments but 5 were given
```

**Comment by iwootten** [comment]
Fixed in #7
